package com.cggcoding.models;


import com.cggcoding.exceptions.DatabaseException;
import com.cggcoding.exceptions.ValidationException;

/**
 * To be used with any object representation of a database model.
 * @author cgrid_000
 *
 */
public interface DatabaseModel {
	
	//XXX Rethink having create() return anything since it isn't static and having moved the Connection to the model, the auto-generated id should be updated internally, so no need to return a new object, that just wastes memory
	/**Saves new record of the model in the database and sets the models id with the id that was auto-generated by the database
	 * @return 
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	Object create() throws ValidationException, DatabaseException;
	
	//TODO make a create(Connection cn) interface method?
	
	/**Updates the record for the model in the database
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	void update() throws ValidationException, DatabaseException;
	
	//TODO make an update(Connection cn) interface method?
	
	/**Deleted the record of the model from the database
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	void delete() throws ValidationException, DatabaseException;

}
