package com.cggcoding.models;

import java.util.List;

import com.cggcoding.exceptions.DatabaseException;
import com.cggcoding.exceptions.ValidationException;

/**
 * To be used with any object representation of a database model.
 * @author cgrid_000
 *
 */
public interface DatabaseModel {
	
	/**Saves new record of the model in the database and sets the models id with the id that was auto-generated by the database
	 * @return TODO
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	Object saveNew() throws ValidationException, DatabaseException;
	
	/**Updates the record for the model in the database
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	void update() throws ValidationException, DatabaseException;
	
	/**Deleted the record of the model from the database
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	void delete() throws ValidationException, DatabaseException;
	

	/**Copies the object the specified number of times
	 * @param numberOfCopies Number of copies desired of the model
	 * @return A list of the copied object
	 */
	List<Object> copy(int numberOfCopies);
}
