package com.cggcoding.models;

import java.util.ArrayList;
import java.util.List;

import org.apache.tomcat.jdbc.pool.DataSource;

import com.cggcoding.exceptions.DatabaseException;
import com.cggcoding.exceptions.ValidationException;
import com.cggcoding.utils.database.DatabaseActionHandler;
import com.cggcoding.utils.database.MySQLActionHandler;

public abstract class User {
	private int userID;
	private String email;
	private List<String> roles;
	String role;
	private List<TreatmentPlan> treatmentPlanList;
	private DatabaseActionHandler databaseActionHandler;
	
	public User (int userID, String email){
		this.userID = userID;
		this.email = email;
		roles = new ArrayList<>();
		this.treatmentPlanList = new ArrayList<>();
		databaseActionHandler = new MySQLActionHandler();
	}

	public int getUserID(){
		return userID;
	}

	public String getEmail() {
		return email;
	}

	public List<String> getRoles(){
		return roles;
	}
	
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean hasRole(String roleName){

		for(String name : roles){
			if (name.equals(roleName)){
				return true;
			}
		}
		return false;
	}

	public void addRole(String roleName){
		roles.add(roleName);
	}

	public void setTreatmentPlanList(List<TreatmentPlan> treatmentPlanList){
		this.treatmentPlanList = treatmentPlanList;
	}

	public List<TreatmentPlan> getTreatmentPlanList(){
		return treatmentPlanList;
	}

	public void addTreatmentPlan(TreatmentPlan treatmentPlan){
		this.treatmentPlanList.add(treatmentPlan);
	}

	public TreatmentPlan getTreatmentPlan(int treatmentPlanID){
		return treatmentPlanList.get(treatmentPlanID);
	}
	
	
	/**
	 * Saves a new custom treatment issue in the database. This only accessible for user roles of Therapist and Admin as they
	 * are the only ones who can create and modify the elements of a treatment plan
	 * @param datasource
	 * @param treatmentIssue
	 * @return TreatmentIssue that has the autogenerated issueID that was created after the database insert
	 * @throws ValidationException
	 * @throws DatabaseException
	 */
	public TreatmentIssue createTreatmentIssue(DataSource datasource, TreatmentIssue treatmentIssue) throws ValidationException, DatabaseException {
		databaseActionHandler = new MySQLActionHandler();
		return databaseActionHandler.treatmentIssueCreate(treatmentIssue);
	}
	
	
	@Override
	public String toString(){
		return "User id:" + email + ", User email: " + email;
	}

	
}
