version: '3.8'  # Specify the version of Docker Compose

services:
  db:
    image: mysql:8.0.33
    container_name: inbetween-mysql8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inbetween
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
    networks:
      - inbetween2-network

  web:
    image: tomcat:8.5.100-jre8 # just doing tomcat:8 resulted in tomcat 8.5.100
    container_name: inbetween-tomcat8jre8
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile to build the image
    command: ["catalina.sh", "run"]
    ports:
      - "8080:8080"
    networks:
      - inbetween2-network
    depends_on:
      - db  # Ensure the database is started before the web service

volumes:
  db_data:  # Named volume for MySQL data persistence

networks:
  inbetween2-network:  # Custom network for communication between containers
