package com.cggcoding.models.tasktypes;

import com.cggcoding.models.Task;
import com.cggcoding.models.Updateable;

import java.util.Random;

public class CognitiveTask extends Task implements Updateable{
	private String automaticThought;
	private String alternativeThought;
	private int preSUDS;
	private int postSUDS;

	public CognitiveTask (int taskID){
		super(taskID);
	}

	public CognitiveTask (int taskID, int userID, String name, String instructions){
		super(taskID, userID, name, instructions);
	}

	public CognitiveTask (int taskID, int userID, int taskSetID, String name, String instructions){
		super(taskID, userID, taskSetID, name, instructions);
	}
	
	public CognitiveTask (int taskID, int userID, int taskSetID, String name, String instructions, String automaticThought, String alternativeThought, int preSUDS, int postSUDS){
		super(taskID, userID, taskSetID, name, instructions);
		this.automaticThought = automaticThought;
		this.alternativeThought = alternativeThought;
		this.preSUDS = preSUDS;
		this.postSUDS = postSUDS;
	}

	//static factory method
	/*public static CognitiveTask newInstance(int taskSetID, String name, String description){
		//this.taskID = TODO replace Random with call to database to create the task and get the autogenerated taskID
		int taskID = Math.abs(new Random(10000).nextInt());

		return new CognitiveTask(taskID, taskSetID, name, description);
	}*/

	
	public String getAutomaticThought() {
		return automaticThought;
	}
	public void setAutomaticThought(String automaticThought) {
		this.automaticThought = automaticThought;
	}
	public String getAlternativeThought() {
		return alternativeThought;
	}
	public void setAlternativeThought(String alternativeThought) {
		this.alternativeThought = alternativeThought;
	}
	public int getPreSUDS() {
		return preSUDS;
	}
	public void setPreSUDS(int preSUDS) {
		this.preSUDS = preSUDS;
	}
	public int getPostSUDS() {
		return postSUDS;
	}
	public void setPostSUDS(int postSUDS) {
		this.postSUDS = postSUDS;
	}


	//TODO Do I keep this DB call here or go back to having it in Stage?
	@Override
	public boolean updateData(Task taskWithNewData) {
		//update universal properties
		this.setCompleted(taskWithNewData.isCompleted());
		this.setDateCompleted(taskWithNewData.getDateCompleted());


		//CognitiveTask cogTask = (CognitiveTask)persistentTask;
		CognitiveTask newData = (CognitiveTask)taskWithNewData;

		this.setAlternativeThought(newData.getAlternativeThought());
		this.setAutomaticThought(newData.getAutomaticThought());

		//updateCogTask DB call goes here

		return true;//TODO returns true if DB update was success
	}

}
