package com.cggcoding.models.tasktypes;

import com.cggcoding.exceptions.DatabaseException;
import com.cggcoding.exceptions.ValidationException;
import com.cggcoding.models.DatabaseModel;
import com.cggcoding.models.Task;

import java.util.List;
import java.util.Random;

public class PsychEdTask extends Task implements DatabaseModel{




	public PsychEdTask(int taskID, int userID) {
		super(taskID, userID);
	}

	public PsychEdTask(int taskID, int userID, String title, String instructions) {
		super(taskID, userID, title, instructions);
	}

	public PsychEdTask(int taskID, int userID, int taskSetID, String title, String instructions) {
		super(taskID, userID, taskSetID, title, instructions);
	}

	//static factory method
	public static PsychEdTask newInstance(int taskSetID, String title, String instructions){
		//this.taskID = TODO replace Random with call to database to create the task and get the autogenerated taskID
		int taskID = Math.abs(new Random(10000).nextInt());

		return new PsychEdTask(taskID, taskSetID, title, instructions);
	}

	//TODO DELETE this after db integration done - maybe move to update()
	public boolean updateData(Task taskWithNewData) {
		//update universal properties
		this.setCompleted(taskWithNewData.isCompleted());
		this.setDateCompleted(taskWithNewData.getDateCompleted());

		//updateCogTask DB call goes here

		return true;//TODO returns true if DB update was success
	}

	@Override
	protected boolean updateAdditionalData() {
		return true;//no additional data to update
	}

	@Override
	protected void loadAdditionalData() {
		// TODO Auto-generated method stub
	}
	
	@Override
	public void saveNew() throws ValidationException, DatabaseException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void update() throws ValidationException, DatabaseException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete() throws ValidationException, DatabaseException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<Object> copy(Object o, int numberOfCopies) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected void saveNewAdditionalData() throws DatabaseException, ValidationException {
		// TODO Auto-generated method stub
		
	}

	
}
