package com.cggcoding.models.tasktypes;

import com.cggcoding.exceptions.DatabaseException;
import com.cggcoding.exceptions.ValidationException;
import com.cggcoding.models.DatabaseModel;
import com.cggcoding.models.Task;

import java.util.List;
import java.util.Random;

public class RelaxationTask extends Task implements DatabaseModel{
	
	private int durationInMinutes;


	public RelaxationTask(int taskID, int userID) {
		super(taskID, userID);
	}

	public RelaxationTask(int taskID, int userID, String title, String instructions, int duration) {
		super(taskID, userID, title, instructions);
		durationInMinutes = duration;
	}

	public RelaxationTask(int taskID, int userID, int taskSetID, String title, String instructions, int duration) {
		super(taskID, userID, taskSetID, title, instructions);
		durationInMinutes = duration;
	}

	//static factory method
	public static RelaxationTask newInstance(int taskSetID, String title, String instructions, int durationInMinutes){
		//this.taskID = TODO replace Random with call to database to create the task and get the autogenerated taskID
		int taskID = Math.abs(new Random(10000).nextInt());

		return new RelaxationTask(taskID, taskSetID, title, instructions, durationInMinutes);
	}

	public int getDurationInMinutes(){
		return this.durationInMinutes;
	}

	//TODO DELETE this after db integration done - maybe move to update()?
	public boolean updateData(Task taskWithNewData) {
		//update universal properties
		this.setCompleted(taskWithNewData.isCompleted());
		this.setDateCompleted(taskWithNewData.getDateCompleted());

		//updateCogTask DB call goes here

		return true;//TODO returns true if DB update was success
	}

	@Override
	public boolean updateAdditionalData() {
		// TODO if keeping this class, implement method for updating additional data 
		return false;
	}

	@Override
	public void saveNew() throws ValidationException, DatabaseException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void update() throws ValidationException, DatabaseException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete() throws ValidationException, DatabaseException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<Object> copy(Object o, int numberOfCopies) {
		// TODO Auto-generated method stub
		return null;
	}
}
