package com.cggcoding.models.tasktypes;

import com.cggcoding.models.Task;
import com.cggcoding.models.Updateable;

import java.util.Random;

public class RelaxationTask extends Task implements Updateable{
	
	private int durationInMinutes;

	public RelaxationTask(int taskID){
		super(taskID);
	}

	public RelaxationTask(String name, String description, int duration) {
		super(name, description);
		durationInMinutes = duration;
	}

	public RelaxationTask(int taskID, String name, String description, int duration) {
		super(taskID, name, description);
		durationInMinutes = duration;
	}

	public RelaxationTask(int taskID, int taskSetID, String name, String description, int duration) {
		super(taskID, taskSetID, name, description);
		durationInMinutes = duration;
	}

	//static factory method
	public static RelaxationTask newInstance(int taskSetID, String name, String description, int durationInMinutes){
		//this.taskID = TODO replace Random with call to database to create the task and get the autogenerated taskID
		int taskID = Math.abs(new Random(10000).nextInt());

		return new RelaxationTask(taskID, taskSetID, name, description, durationInMinutes);
	}

	public int getDurationInMinutes(){
		return this.durationInMinutes;
	}

	@Override
	public boolean updateData(Task taskWithNewData) {
		//update universal properties
		this.setCompleted(taskWithNewData.isCompleted());
		this.setDateCompleted(taskWithNewData.getDateCompleted());

		//updateCogTask DB call goes here

		return true;//TODO returns true if DB update was success
	}
}
